apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: loki-template
message: |-
  The following service(s) have been created in your project: ${LOKI_SERVICE_NAME}.
  For more information about using this template, including OpenShift considerations, contact the rocketchat community.
metadata:
  annotations:
    description: |-
      loki Template for use in OpenShift 201 lab. 
      WARNING: Any configuration stored will be lost upon pod destruction. ConfigMaps should be used for codified configuration. 
    iconClass: icon-other-unknown
    openshift.io/display-name: loki-openshift201
    openshift.io/documentation-url: https://github.com/bcdevops/devops-platform-workshops
    openshift.io/long-description: This template provides a sample loki configuration for lab purposes.
    openshift.io/provider-display-name: BCDevOps
    openshift.io/support-url: https://github.com/bcdevops/
    tags: monitoring,loki
  name: loki-template
objects: 
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${LOKI_SERVICE_NAME}
    labels:
      app: ${LOKI_SERVICE_NAME}
  data:
    loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQpjaHVua19zdG9yZV9jb25maWc6CiAgbWF4X2xvb2tfYmFja19wZXJpb2Q6IDAKaW5nZXN0ZXI6CiAgY2h1bmtfYmxvY2tfc2l6ZTogMjYyMTQ0CiAgY2h1bmtfaWRsZV9wZXJpb2Q6IDE1bQogIGxpZmVjeWNsZXI6CiAgICByaW5nOgogICAgICBrdnN0b3JlOgogICAgICAgIHN0b3JlOiBpbm1lbW9yeQogICAgICByZXBsaWNhdGlvbl9mYWN0b3I6IDEKbGltaXRzX2NvbmZpZzoKICBlbmZvcmNlX21ldHJpY19uYW1lOiBmYWxzZQpzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgLSBmcm9tOiAiMjAxOC0wNC0xNSIKICAgIGluZGV4OgogICAgICBwZXJpb2Q6IDE2OGgKICAgICAgcHJlZml4OiBpbmRleF8KICAgIG9iamVjdF9zdG9yZTogZmlsZXN5c3RlbQogICAgc2NoZW1hOiB2OQogICAgc3RvcmU6IGJvbHRkYgpzZXJ2ZXI6CiAgaHR0cF9saXN0ZW5fcG9ydDogMzEwMApzdG9yYWdlX2NvbmZpZzoKICBib2x0ZGI6CiAgICBkaXJlY3Rvcnk6IC9kYXRhL2xva2kvaW5kZXgKICBmaWxlc3lzdGVtOgogICAgZGlyZWN0b3J5OiAvZGF0YS9sb2tpL2NodW5rcwo=
- apiVersion: v1
  kind: Service
  metadata:
    name: ${LOKI_SERVICE_NAME}
    labels:
      app: ${LOKI_SERVICE_NAME}
    annotations:
      {}
  spec:
    type: ClusterIP
    ports:
      - port: 3100
        protocol: TCP
        name: http-metrics
        targetPort: http-metrics
    selector:
      app: ${LOKI_SERVICE_NAME}
      release: ${LOKI_SERVICE_NAME}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${LOKI_SERVICE_NAME}
    labels:
      app: ${LOKI_SERVICE_NAME}
    annotations:
      {}
  spec:
    replicas: 1
    minReadySeconds: 0
    selector:
      matchLabels:
        app: ${LOKI_SERVICE_NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${LOKI_SERVICE_NAME}
        annotations:
          checksum/config: 4e6249648052ed8050df59448966dd422bc0a0cd8d13ed12a72e7f243b1fcdbc
          prometheus.io/port: http-metrics
          prometheus.io/scrape: "true"
          our-awesome-metadata: "nothing to see here"
      spec:
        serviceAccountName: default
        containers:
          - name: loki
            image: "grafana/loki:latest"
            imagePullPolicy: Always
            args:
              - "-config.file=/etc/loki/loki.yaml"            
            volumeMounts:
              - name: config
                mountPath: /etc/loki
              - name: storage
                mountPath: "/data"
                subPath: 
            ports:
              - name: http-metrics
                containerPort: 3100
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 45
            readinessProbe:
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 45
            resources:
              {}
            securityContext:
              readOnlyRootFilesystem: true
            env:
              - name: JAEGER_AGENT_HOST
                value: ""
        terminationGracePeriodSeconds: 30
        volumes:
          - name: config
            secret:
              secretName: ${LOKI_SERVICE_NAME}
          - name: storage
            emptyDir: {}
parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The namespace this templated is deployed into.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed.
  displayName: Loki Service Name
  name: LOKI_SERVICE_NAME
  required: true
  value: loki