#!/usr/bin/env groovy

//comment
//ENV Vars
def TOOLS_NAMESPACE = "4zq6uj-filiy-ocp201-tst-tools"
def DEV_NAMESPACE = "4zq6uj-filiy-ocp201-tst-dev"
def PROD_NAMESPACE = "4zq6uj-filiy-ocp201-tst-prod"
def LOKI_SERVICE  = "loki"

//Pipeline
node {
            stage ('Deploy Loki to Dev'){
                dir ('simple_pipeline') {
                    checkout scm
                    sh "oc process -f openshift201/templates/loki.yaml -p NAME=${LOKI_SERVICE} | oc apply -f - -n ${DEV_NAMESPACE}"

                }
            }
    }